# Generated by Django 5.1.7 on 2025-05-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "feature_image",
                    models.ImageField(blank=True, null=True, upload_to="news/"),
                ),
                ("description", models.TextField()),
                ("third_party_link", models.URLField(blank=True, null=True)),
                ("publish_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArchivedNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
            ],
        ),
    ]
