# Generated by Django 5.1.7 on 2025-05-07 07:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_is_archived"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="is_archived",
            new_name="archived",
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
