# Generated by Django 5.2 on 2025-05-07 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_description_alter_news_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'News Log', 'verbose_name_plural': 'News Logs'},
        ),
        migrations.AlterField(
            model_name='newslog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newslog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=50),
        ),
        migrations.AlterField(
            model_name='newslog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
