# Generated by Django 5.2 on 2025-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_newslog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=50),
        ),
    ]
