# Generated by Django 5.1.7 on 2025-04-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
