# Generated by Django 5.2 on 2025-04-04 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_delete_notificationchannel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterfield',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voterfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voterfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Select')], default='text', max_length=50),
        ),
    ]
