# Generated by Django 5.2 on 2025-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voterfield_created_at_voterfield_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.IntegerField(default=0, verbose_name='AGE'),
        ),
        migrations.AddField(
            model_name='voter',
            name='assembly',
            field=models.CharField(default='', max_length=255, verbose_name='ASSEMBLY'),
        ),
        migrations.AddField(
            model_name='voter',
            name='card_no',
            field=models.CharField(default='', max_length=50, verbose_name='CARD NO'),
        ),
        migrations.AddField(
            model_name='voter',
            name='caste',
            field=models.CharField(default='', max_length=100, verbose_name='CASTE'),
        ),
        migrations.AddField(
            model_name='voter',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='CATEGORY'),
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='GENDER'),
        ),
        migrations.AddField(
            model_name='voter',
            name='hno',
            field=models.CharField(default='', max_length=50, verbose_name='HNO'),
        ),
        migrations.AddField(
            model_name='voter',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='LOCATION'),
        ),
        migrations.AddField(
            model_name='voter',
            name='mandal',
            field=models.CharField(default='', max_length=255, verbose_name='MANDAL'),
        ),
        migrations.AddField(
            model_name='voter',
            name='mlc_constituency',
            field=models.CharField(default='', max_length=255, verbose_name='MLC CONSTITUENCY'),
        ),
        migrations.AddField(
            model_name='voter',
            name='mobile_no',
            field=models.CharField(default='', max_length=15, verbose_name='MOBILE NO'),
        ),
        migrations.AddField(
            model_name='voter',
            name='party',
            field=models.CharField(default='', max_length=100, verbose_name='PARTY'),
        ),
        migrations.AddField(
            model_name='voter',
            name='ps_address',
            field=models.TextField(default='', verbose_name='PS ADDRESS'),
        ),
        migrations.AddField(
            model_name='voter',
            name='psno',
            field=models.CharField(default='', max_length=50, verbose_name='PSNO'),
        ),
        migrations.AddField(
            model_name='voter',
            name='rel_name',
            field=models.CharField(default='', max_length=255, verbose_name='REL NAME'),
        ),
        migrations.AddField(
            model_name='voter',
            name='relation',
            field=models.CharField(default='', max_length=255, verbose_name='RELATION'),
        ),
        migrations.AddField(
            model_name='voter',
            name='sno',
            field=models.CharField(default='', max_length=50, verbose_name='SNO'),
        ),
        migrations.AddField(
            model_name='voter',
            name='street',
            field=models.CharField(default='', max_length=255, verbose_name='STREET'),
        ),
        migrations.AddField(
            model_name='voter',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TOWN'),
        ),
        migrations.AddField(
            model_name='voter',
            name='verify_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='VERIFY STATUS'),
        ),
        migrations.AddField(
            model_name='voter',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VILLAGE'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_name',
            field=models.CharField(default='', max_length=255, verbose_name='VOTER NAME'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_status',
            field=models.CharField(default='', max_length=50, verbose_name='VOTER STATUS'),
        ),
    ]
