# Generated by Django 5.2 on 2025-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_voter_age_voter_assembly_voter_card_no_voter_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
