# Generated by Django 5.2 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_alter_voter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='AGE'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='assembly',
            field=models.CharField(max_length=255, verbose_name='ASSEMBLY'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CARD NO'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CASTE'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='GENDER'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='hno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HNO'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LOCATION'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='mandal',
            field=models.CharField(max_length=255, verbose_name='MANDAL'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='mlc_constituency',
            field=models.CharField(max_length=255, verbose_name='MLC CONSTITUENCY'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='mobile_no',
            field=models.CharField(max_length=15, verbose_name='MOBILE NO'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PARTY'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ps_address',
            field=models.TextField(blank=True, null=True, verbose_name='PS ADDRESS'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='psno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PSNO'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='rel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='REL NAME'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RELATION'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='sno',
            field=models.CharField(max_length=50, verbose_name='SNO'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='STREET'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='verify_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VERIFY STATUS'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VOTER NAME'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VOTER STATUS'),
        ),
    ]
