# Generated by Django 5.2 on 2025-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_created_by_alter_blog_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for the blog post', null=True, upload_to='blog_images/', verbose_name='Featured Image'),
        ),
    ]
