# Generated by Django 5.2 on 2025-05-12 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Main content of the blog post'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=ckeditor.fields.RichTextField(help_text='A brief summary of the blog post'),
        ),
    ]
