# Generated by Django 5.2 on 2025-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('temple', models.CharField(choices=[('Sri Mahakaaleshwar Mandir', 'Sri Mahakaaleshwar Mandir'), ('Tirumala Tirupati Devasthanam', 'Tirumala Tirupati Devasthanam'), ('Dwaraka Tirumala Devasthanam', 'Dwaraka Tirumala Devasthanam'), ('Sree Padmanabha Swamy Devasthanam', 'Sree Padmanabha Swamy Devasthanam'), ('Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam', 'Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam'), ('Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple', 'Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple'), ('Shri Shirdi Sayee Samsthan', 'Shri Shirdi Sayee Samsthan'), ('Sabarimala Sree Ayyappa Devasthanam', 'Sabarimala Sree Ayyappa Devasthanam'), ('Shree Jagannath Temple', 'Shree Jagannath Temple'), ('Shri Kashi Vishwanath Temple', 'Shri Kashi Vishwanath Temple'), ('Swayambhu Sri Varasiddhi Vinayaka Swamy', 'Swayambhu Sri Varasiddhi Vinayaka Swamy'), ('Sri Kamakshi Ambal Devasthanam', 'Sri Kamakshi Ambal Devasthanam'), ('Ram Lala Ayodha', 'Ram Lala Ayodha'), ('Arulmigu Arunachaleswarar Temple', 'Arulmigu Arunachaleswarar Temple')], max_length=100)),
                ('num_persons', models.PositiveIntegerField()),
                ('visit_date', models.DateField()),
                ('id_proof_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('VOTER', 'Voter ID'), ('PAN', 'PAN Card'), ('DL', 'Driving License')], max_length=10)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pass',
                'verbose_name_plural': 'Passes',
            },
        ),
    ]
