# Generated by Django 5.2 on 2025-04-15 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_pass_approved_at_pass_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pass', 'verbose_name_plural': 'Passes'},
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='approved_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='pass',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pass',
            name='id_proof_number',
            field=models.CharField(max_length=50, verbose_name='ID Proof Number'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='id_proof_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('VOTER', 'Voter ID'), ('PAN', 'PAN Card'), ('DL', 'Driving License')], max_length=10, verbose_name='ID Proof Type'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='temple',
            field=models.CharField(choices=[('Sri Mahakaaleshwar Mandir', 'Sri Mahakaaleshwar Mandir'), ('Tirumala Tirupati Devasthanam', 'Tirumala Tirupati Devasthanam')], max_length=100),
        ),
    ]
