# Generated by Django 5.2 on 2025-04-15 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_pass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='num_persons',
            field=models.PositiveIntegerField(help_text='Maximum 6 persons allowed per pass', validators=[django.core.validators.MinValueValidator(1, message='Number of persons must be at least 1'), django.core.validators.MaxValueValidator(6, message='Maximum 6 persons allowed per pass')]),
        ),
        migrations.AlterField(
            model_name='pass',
            name='temple',
            field=models.CharField(choices=[('Sri Mahakaaleshwar Mandir', 'Sri Mahakaaleshwar Mandir'), ('Tirumala Tirupati Devasthanam', 'Tirumala Tirupati Devasthanam'), ('Dwaraka Tirumala Devasthanam', 'Dwaraka Tirumala Devasthanam'), ('Sree Padmanabha Swamy Devasthanam', 'Sree Padmanabha Swamy Devasthanam'), ('Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam', 'Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam'), ('Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple', 'Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple'), ('Shri Shirdi Sayee Samsthan', 'Shri Shirdi Sayee Samsthan'), ('Sabarimala Sree Ayyappa Devasthanam', 'Sabarimala Sree Ayyappa Devasthanam'), ('Shree Jagannath Temple', 'Shree Jagannath Temple'), ('Shri Kashi Vishwanath Temple', 'Shri Kashi Vishwanath Temple'), ('Swayambhu Sri Varasiddhi Vinayaka Swamy', 'Swayambhu Sri Varasiddhi Vinayaka Swamy'), ('Sri Kamakshi Ambal Devasthanam', 'Sri Kamakshi Ambal Devasthanam'), ('Ram Lala Ayodha', 'Ram Lala Ayodha'), ('Arulmigu Arunachaleswarar Temple', 'Arulmigu Arunachaleswarar Temple')], max_length=100),
        ),
    ]
