# Generated by Django 5.2 on 2025-04-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtemplate_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_id',
            field=models.CharField(blank=True, help_text='Edumarc SMS Template ID', max_length=100, null=True),
        ),
    ]
