# Generated by Django 5.2 on 2025-05-09 12:14

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_images/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('caption', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('event', 'Event Photos'), ('campaign', 'Campaign Videos'), ('interview', 'Interviews'), ('behind_scenes', 'Behind-the-Scenes')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Enter tags separated by commas', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='swastik404-ai', editable=False, max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Media_Management', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
